### ISSUE TITLE
Pragmas Error

### ISSUE THREAD

**Issue by HamasWaqar** [UniversalGRAMM/UGRAMM#18] opened 2024-10-09 23:31 UTC
Hi @ombhilare999, 

While updating some of the benchmarks, I noticed that these new benchmarks are not able to run on UGRAMM. More specifically, these benchmarks are causing UGRAMM to early exit due to the pragma error seen below.

![image](https://github.com/user-attachments/assets/9d32abdf-cdb7-4ed8-8a8c-60fc108c35ab)

The pragmas used are the same as the ones used for our Conv_Balance benchmarks. On the surface, everything looks identical, so I was wondering if you knew what the issue could be. 

Branch name: add_all_benchmarks
Script to update the benchmarks: benchmark_modification.py
Benchmark in question that is creating the error: Kernels/Conv_nonBalance/conv_nounroll.dot

**Comment by ombhilare999** [comment] 2024-10-09 23:53
Hi @HamasWaqar ,

I am not able to reproduce this error, in my case the benchmark you provided it works as well in terms of Pragma.

Command run: `./run_ugramm.sh 15 8 8 Kernels/Conv_nonBalance/conv_nounroll.dot config.json`

![image](https://github.com/user-attachments/assets/1f676235-7dac-4da8-9f6a-cedb5e327c1b)

**Comment by ombhilare999** [comment] 2024-10-12 06:22
Hi @HamasWaqar ,
Can we close this if resolved?

**Closed** 2024-10-14 16:19 UTC
